
version: '3.1'

services:
  dailyapp:
    container_name: docker_blog_react
    image: docker_blog_react
    restart: always
    build: ./
    ports:
      - "5555:4444"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/blog?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    networks:
      - springmysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    ports:
      - 3307:3306
    expose:
      - "3307"

    networks:
      - springmysql
    environment:
      - MYSQL_ROOT_PASSWORD=159951
      - MYSQL_DATABASE=blog
      - MYSQL_USER=batuhan
      - MYSQL_PASSWORD=159951
    restart: unless-stopped

networks:
  springmysql:
    name: springmysql
    driver: bridge



    #services:
    #  mysql:
    #    image: 'mysql:latest'
    #    environment:
    #      - 'MYSQL_DATABASE=mydatabase'
    #      - 'MYSQL_PASSWORD=secret'
    #      - 'MYSQL_ROOT_PASSWORD=verysecret'
    #      - 'MYSQL_USER=myuser'
    #    ports:
    #      - '3306'
